TokenService/v2/TokenProject/src/TokenProject.STS.Identity/Controllers/GrantsController.cs
// Copyright (c) Brock Allen & Dominick Baier. All rights reserved.
// Licensed under the Apache License, Version 2.0. See LICENSE in the project root for license information.

// Original file: https://github.com/IdentityServer/IdentityServer4.Quickstart.UI
// Modified by Jan Škoruba

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IdentityServer4.Events;
using IdentityServer4.Extensions;
using IdentityServer4.Services;
using IdentityServer4.Stores;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TokenProject.STS.Identity.Helpers;
using TokenProject.STS.Identity.ViewModels.Grants;

namespace TokenProject.STS.Identity.Controllers
{
    /// <summary>
    /// This sample controller allows a user to revoke grants given to clients
    /// </summary>
    [SecurityHeaders]
    [Authorize]
    public class GrantsController : Controller
    {
        private readonly IIdentityServerInteractionService _interaction;
        private readonly IClientStore _clients;
        private readonly IResourceStore _resources;
        private readonly IEventService _events;

        public GrantsController(IIdentityServerInteractionService interaction,
            IClientStore clients,
            IResourceStore resources,
            IEventService events)
        {
            _interaction = interaction;
            _clients = clients;
            _resources = resources;
            _events = events;
        }

        /// <summary>
        /// Show list of grants
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View("Index", await BuildViewModelAsync());
        }

        /// <summary>
        /// Handle postback to revoke a client
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Revoke(string clientId)
        {
            await _interaction.RevokeUserConsentAsync(clientId);
            await _events.RaiseAsync(new GrantsRevokedEvent(User.GetSubjectId(), clientId));

            return RedirectToAction("Index");
        }

        private async Task<GrantsViewModel> BuildViewModelAsync()
        {
            var grants = await _interaction.GetAllUserGrantsAsync();

            var list = new List<GrantViewModel>();
            foreach (var grant in grants)
            {
                var client = await _clients.FindClientByIdAsync(grant.ClientId);
                if (client != null)
                {
                    var resources = await _resources.FindResourcesByScopeAsync(grant.Scopes);

                    var item = new GrantViewModel()
                    {
                        ClientId = client.ClientId,
                        ClientName = client.ClientName ?? client.ClientId,
                        ClientLogoUrl = client.LogoUri,
                        ClientUrl = client.ClientUri,
                        Description = grant.Description,
                        Created = grant.CreationTime,
                        Expires = grant.Expiration,
                        IdentityGrantNames = resources.IdentityResources.Select(x => x.DisplayName ?? x.Name).ToArray(),
                        ApiGrantNames = resources.ApiScopes.Select(x => x.DisplayName ?? x.Name).ToArray()
                    };

                    list.Add(item);
                }
            }

            return new GrantsViewModel
            {
                Grants = list
            };
        }
    }
}

TokenService/v2/TokenProject/src/TokenProject.STS.Identity/ViewComponents/IdentityServerAdminLinkViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TokenProject.STS.Identity.Configuration.Interfaces;

namespace TokenProject.STS.Identity.ViewComponents
{
    public class IdentityServerAdminLinkViewComponent : ViewComponent
    {
        private readonly IRootConfiguration _configuration;

        public IdentityServerAdminLinkViewComponent(IRootConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IViewComponentResult Invoke()
        {
            var identityAdminUrl = _configuration.AdminConfiguration.IdentityAdminBaseUrl;

            return View(model: identityAdminUrl);
        }
    }
}

TokenService/v2/TokenProject/src/TokenProject.STS.Identity/Views/Shared/Redirect.cshtml
@model TokenProject.STS.Identity.ViewModels.Account.RedirectViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<h1>@Localizer["Title"]</h1>
<p>@Localizer["SubTitle"]</p>
<meta http-equiv="refresh" content="0;url=@Model.RedirectUrl" data-url="@Model.RedirectUrl">
<script src="~/js/signin-redirect.js"></script>

TokenService/v2/TokenProject/src/TokenProject.STS.Identity/Views/Shared/_Layout.cshtml
@using IdentityServer4.Extensions
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@using TokenProject.Admin.EntityFramework.Shared.Entities.Identity
@using TokenProject.STS.Identity.Configuration.Interfaces
@inject IRootConfiguration RootConfiguration
@inject IViewLocalizer Localizer
@{
    string name = null;
    if (!true.Equals(ViewData["signed-out"]))
    {
        name = Context.User?.GetDisplayName();
    }
}

@inject SignInManager<UserIdentity> SignInManager
@{
    var hasExternalLogins = (await SignInManager.GetExternalAuthenticationSchemesAsync()).Any();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@RootConfiguration.AdminConfiguration.PageTitle</title>
    <link rel="icon" type="image/x-icon" href="@UrlHelper.Content(RootConfiguration.AdminConfiguration.FaviconUri)" />
    <link rel="shortcut icon" type="image/x-icon" href="@UrlHelper.Content(@RootConfiguration.AdminConfiguration.FaviconUri)" />

    <environment include="Development">
        <link href="~/dist/css/bundle.min.css" asp-append-version="true" rel="stylesheet" />
        @await Html.PartialAsync("Common/ThemeResources")
        <link href="~/dist/css/web.css" asp-append-version="true" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link href="~/dist/css/bundle.min.css" asp-append-version="true" rel="stylesheet" />
        @await Html.PartialAsync("Common/ThemeResources")
        <link href="~/dist/css/web.min.css" asp-append-version="true" rel="stylesheet" />
    </environment>

    @if (!string.IsNullOrEmpty(RootConfiguration.AdminConfiguration.CustomThemeCss))
    {
        <link href="@UrlHelper.Content(RootConfiguration.AdminConfiguration.CustomThemeCss)" asp-append-version="true" rel="stylesheet" />
    }

    @await RenderSectionAsync("styles", required: false)
</head>
<body>

    <div class="menu d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 border-bottom box-shadow">
        <!--Site name -->
        <h3 class="menu-logo my-0 mr-md-auto font-weight-normal"><a class="logo" asp-area="" asp-controller="Home" asp-action="Index">@RootConfiguration.AdminConfiguration.PageTitle</a></h3>
        <!--Menu item -->
        @if (User.Identity.IsAuthenticated && !string.IsNullOrEmpty(name))
        {
            <!--Menu item -->
            <vc:identity-server-admin-link></vc:identity-server-admin-link>

            <!--Menu item -->
            <div class="menu-item my-2 my-md-0 mr-md-3 dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    @Localizer["Settings"] - @name
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" asp-controller="Manage" asp-action="Index">@Localizer["ManageProfile"]</a>
                    <a class="dropdown-item" asp-controller="Manage" asp-action="PersonalData">@Localizer["ManagePersonalData"]</a>
                    @if (hasExternalLogins)
                    {
                        <a class="dropdown-item" asp-controller="Manage" asp-action="ExternalLogins">@Localizer["ExternalLogins"]</a>
                    }
                    <a class="dropdown-item" asp-controller="Manage" asp-action="TwoFactorAuthentication">@Localizer["2FA"]</a>
                    <a class="dropdown-item" asp-controller="Manage" asp-action="ChangePassword">@Localizer["ChangePassword"]</a>
                    <a class="dropdown-item" asp-controller="Grants" asp-action="Index">@Localizer["Grants"]</a>
                </div>
            </div>

            <a class="menu-item my-2 btn btn-outline-primary" asp-action="Logout" asp-controller="Account">@Localizer["Signout"]</a>
        }

        <!--Menu button - show in < MD -->
        <a class="my-2 btn btn-outline-primary menu-button" href="#">
            <span class="oi oi-menu" title="menu" aria-hidden="true"></span> @Localizer["Menu"]
        </a>
    </div>

    <div class="container">
        @RenderBody()

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-6 col-md">
                    @RootConfiguration.AdminConfiguration.PageTitle
                    <small class="d-block mb-3 text-muted">@Localizer["FooterCopyright"] @DateTime.Now.Year - @await Html.PartialAsync("Common/ApplicationVersion")</small>
                </div>
                <div class="col-md-3 text-right">
                    @await Html.PartialAsync("Common/SelectTheme")
                </div>
                <div class="col-md-3 text-right">
                    @await Html.PartialAsync("Common/SelectLanguage")
                </div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/dist/js/bundle.min.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/dist/js/bundle.min.js" asp-append-version="true"></script>
    </environment>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

TokenService/v2/TokenProject/src/TokenProject.STS.Identity/Views/Shared/_ScopeListItem.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model TokenProject.STS.Identity.ViewModels.Consent.ScopeViewModel

<li class="list-group-item">
	<div class="toggle-button__input">
		<toggle-button>
			<input class="consent-scopecheck"
				   type="checkbox"
				   name="ScopesConsented"
				   id="scopes_@Model.Value"
				   value="@Model.Value"
				   checked="@Model.Checked"
				   disabled="@Model.Required" />
		</toggle-button>
	</div>
	<div class="toggle-button__text">
		@if (Model.Required)
		{
			<input type="hidden"
				   name="ScopesConsented"
				   value="@Model.Value" />
		}
		<strong>@Model.DisplayName</strong>
		@if (Model.Emphasize)
		{
			<i class="fa fa-exclamation-circle"></i>
		}
	</div>
	@if (Model.Required)
	{
		<div class="toggle-button__text">
			<span><em>@Localizer["Required"]</em></span>
		</div>
	}
	@if (Model.Description != null)
	{
		<div class="consent-description">
			<label for="scopes_@Model.Value">@Model.Description</label>
		</div>
	}
</li>

TokenService/v2/TokenProject/src/TokenProject.STS.Identity/Views/Shared/_ValidationSummary.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@if (ViewContext.ModelState.IsValid == false)
{
	<div class="alert alert-danger">
		<strong>@Localizer["Title"]</strong>
		<div asp-validation-summary="All" class="danger"></div>
	</div>
}